config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources :accounts, only: %i[index show edit update destroy]
  resources :vendors
  resources :customers
  resources :custom_mails
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(account)
    # Define abilities for the passed in user here. For example:
    #
    account ||= Account.new
    can :read, :all
    cannot :manage, CustomMail
    can :manage, Account, id: account.id if account.no_letters?
    # Abilities for each role
    can :manage, :all if account.admin?
    can :manage, Vendor, account_id: account.id if account.vendor?
    can :manage, Customer, account_id: account.id if account.customer?
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: { vendor: 0, customer: 1, admin: 2 }
  enum status: { no_letters: 0, got_letter: 1 }
  validates :first_name, presence: true, length: { minimum: 3, maximum: 15 }, on: :update
  validates :last_name, presence: true, length: { minimum: 3, maximum: 15 }, on: :update
  validates :city, presence: true, length: { minimum: 2, maximum: 20 }, on: :update
  validates :age, presence: true, numericality:
    { only_integer: true, greater_than_or_equal_to: 16, less_than_or_equal_to: 99 }, on: :update
  has_one :vendor, dependent: :destroy
  has_one :customer, dependent: :destroy
  after_create :after_create_mail
  ADMIN_EMAIL = 'admin123@mail.com'.freeze
  WELCOME = 'welcome'.freeze
  ADMIN_MAIL_AFTER_CREATE = 'admin_after_create'.freeze
  PROFILE_MAIL = 'profile'.freeze
  PROFILE_MAIL_ADMIN = 'profile_admin'.freeze
  delegate :total_account, to: :typed_model

  def after_create_mail
    AccountMailer.send_mail(WELCOME, email, self).deliver_later
    AccountMailer.send_mail(ADMIN_MAIL_AFTER_CREATE, ADMIN_EMAIL, self).deliver_later
  end

  def self.user_roles
    Account.roles.except(:admin)
  end

  def typed_model
    return vendor if vendor?
    customer
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/custom_mail.rb
class CustomMail < ApplicationRecord
  enum mail_type: { welcome: 0, admin_after_create: 1, profile: 2, profile_admin: 3 }
  validates :subject, presence: true, on: :update
  validates :body, presence: true, on: :update
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :total_account, presence: true
  belongs_to :account, optional: true
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  validates :total_account, presence: true
  belongs_to :account, optional: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  before_action :set_status, only: :update

  def index
    @accounts = Account.all
  end

  def show
    @vendor = account.vendor
    @customer = account.customer
  end

  def update
    if account.update(account_params)
      redirect_to account
    else
      render :edit
    end
  end

  def destroy
    account.destroy
    redirect_to accounts_path
  end

  private

  attr_reader :account

  def set_status
    account.status = 'got_letter'
  end

  def account_params
    params.require(:account).permit(:first_name, :last_name, :city, :age)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  alias current_user current_account

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  def after_sign_in_path_for(*)
    account_path(current_account)
  end

  def after_sign_out_path_for(*)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email role])
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  delegate :account, to: :model, prefix: true

  def create
    model = build_model
    if model.save
      mails_after_registration
      redirect_to model_account
    else
      render :new
    end
  end

  def update
    if update_model
      redirect_to model_account
    else
      render :edit
    end
  end

  private

  def mails_after_registration
    AccountMailer.send_mail(Account::PROFILE_MAIL, model_account.email, model_account).deliver_later
    AccountMailer.send_mail(Account::PROFILE_MAIL_ADMIN, Account::ADMIN_EMAIL, model_account).deliver_later
  end
end

app/controllers/custom_mails_controller.rb
class CustomMailsController < ApplicationController
  load_and_authorize_resource

  def index
    @custom_mails = CustomMail.all
  end

  def show; end

  def edit; end

  def update
    if custom_mail.update(custom_mail_params)
      redirect_to custom_mail
    else
      render :edit
    end
  end

  private

  attr_reader :custom_mail

  def custom_mail_params
    params.require(:custom_mail).permit(:subject, :body, :mail_type, :enabled_by_admin)
  end
end

app/controllers/customers_controller.rb
class CustomersController < BaseController
  load_and_authorize_resource
  delegate :account, to: :customer, prefix: true

  private

  attr_reader :customer

  def customer_params
    params.require(:customer).permit(:total_account)
  end

  def build_model
    current_account.build_customer(customer_params)
  end

  def update_model
    model.update(customer_params)
  end

  def model
    @model ||= customer
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/vendors_controller.rb
class VendorsController < BaseController
  load_and_authorize_resource
  delegate :account, to: :vendor, prefix: true

  private

  attr_reader :vendor

  def vendor_params
    params.require(:vendor).permit(:total_account)
  end

  def build_model
    current_account.build_vendor(vendor_params)
  end

  def update_model
    model.update(vendor_params)
  end

  def model
    @model ||= vendor
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/custom_mails_helper.rb
module CustomMailsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/accounts/edit.html.slim
h1
  |  Edit your profile 
= form_for @account do |f|
  .form-group
    = f.label :first_name
    = f.text_field :first_name, class: 'form-control'
  .form-group
    = f.label :last_name
    = f.text_field :last_name, class: 'form-control'
  .form-group
    = f.label :city
    = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :age
    = f.text_field :age, class: 'form-control'
  .form-group
    = f.submit "Save", class: 'btn btn-primary'
    = link_to "Cancel", accounts_path, class: 'btn btn-outline-primary'

app/views/accounts/index.html.slim
- if current_account.admin?
  h1
    |  All users 
  h2
    | Admins
  - @accounts.admin.each do |account|
    p
      = link_to account.first_name, account_path(account)
      = link_to 'edit', edit_account_path(account)
      = link_to 'delete', account_path(account), method: :delete, data: { confirm: 'Are you sure?' }
  h2
    | Vendors
  - @accounts.vendor.each do |account|
    p
      = link_to account.first_name, account_path(account)
      = link_to 'edit', edit_account_path(account)
      = link_to 'delete', account_path(account), method: :delete, data: { confirm: 'Are you sure?' }
  h2
    | Customers
  - @accounts.customer.each do |account|
    p
      = link_to account.first_name, account_path(account)
      = link_to 'edit', edit_account_path(account)
      = link_to 'delete', account_path(account), method: :delete, data: { confirm: 'Are you sure?' }

app/views/accounts/show.html.slim
h1
  |  Profile 
p
  |  Name: 
  = @account.first_name
p
  |  Last Name: 
  = @account.first_name
p
  |  Age: 
  = @account.age
p
  |  City: 
  = @account.city
- if current_account.admin? || @account.status == 'no_letters'
  |  <div class:'form-group'> 
  = link_to 'Edit', edit_account_path(@account), class: 'btn btn-primary'
- if @account.vendor?
  - if @account.vendor.present?
    p
      |  Account: 
      = @account.vendor.total_account
    p
      |  Sales: 
      = @account.vendor.number_of_sales
    - if @account == current_account || current_account.admin?
      = link_to 'Edit bank account', edit_vendor_path(@vendor), class: 'btn btn-primary'
  - else
    - if @account == current_account || current_account.admin?
      = link_to 'Create Bank account', new_vendor_path(@vendor), class: 'btn btn-primary'
- if @account.customer?
  - if @account.customer.present?
    p
      |  Account: 
      = @account.customer.total_account
    p
      |  Buys: 
      = @account.customer.number_of_buys
    - if @account == current_account || current_account.admin?
      = link_to 'Edit bank account', edit_customer_path(@customer), class: 'btn btn-primary'
  - else
    - if @account == current_account || current_account.admin?
      = link_to 'Create Bank account', new_customer_path(@customer), class: 'btn btn-primary'

app/views/custom_mails/edit.html.slim
- if @custom_mail.mail_type == 'welcome' || @custom_mail.mail_type == 'admin_after_create'
  p
    |  You can use variables 
    = "$<#{Emails::CustomMailFields::NEW_ACCOUNT_VARIABLES.join('>s, %<')}>s"
- else
  p
    |  You can use variables 
    = "%<#{Emails::CustomMailFields::FILLED_ACCOUNT_VARIABLES.join('>s, %<')}>s"
h3
  solid
    |  If you want to use HTML tags or those variables, press 'Source'!
= form_for @custom_mail do |f|
  .form-group
    = f.label :subject
    = f.text_field :subject, class: 'form-control'
  .form-group
    = f.label :body
    = f.cktext_area :body, class: 'form-control', ckeditor: { language: 'eng'}, rows: 40, cols: 60
  .form-group
    = f.select :mail_type, CustomMail.mail_types.keys
  .form-group
    = f.submit "Save", class: 'btn btn-primary'
    = link_to "Cancel", :back, class: 'btn btn-outline-primary'

app/views/custom_mails/index.html.slim
| Mails: 
- @custom_mails.each do |custom_mail|
  .form-group
    p
      = custom_mail.mail_type
      = link_to 'edit', edit_custom_mail_path(custom_mail)
    = form_for custom_mail do |f|
      = f.select :enabled_by_admin, [['Enabled', true], ['Disabled', false]]
      = f.submit "Save", class: 'btn btn-primary'

app/views/custom_mails/show.html.slim
p
  |  Subject: 
  = @custom_mail.subject
p
  |  Body: 
  = @custom_mail.body
= link_to 'Back to mails', custom_mails_path

app/views/customers/_form.html.slim
= form_for @customer do |f|
  .form-group
    = f.text_field :total_account, class: 'form-control'
  .form-group
    = f.submit "Save", class: 'btn btn-primary'
    = link_to "Cancel", :back, class: 'btn btn-outline-primary'

app/views/customers/edit.html.slim
| Edit your bank account 
= render 'form'

app/views/customers/new.html.slim
= render 'form'

app/views/home/index.html.slim
- if account_signed_in?
  - if current_account.admin?
    = link_to 'Accounts', accounts_path
    = link_to 'Mails', custom_mails_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TestApp
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', Ckeditor.cdn_url ,'data-turbolinks-track': 'reload'
  body
    .container
      nav.navbar.navbar-light.bg-light
        ul.nav.navbar-nav
          li.nav-item.active
            |  <a class="nav-link" href="
            = root_path
            | "> Home page 
        .container-group
          - if account_signed_in?
            = link_to 'Profile', current_account
            = link_to 'Sign out', destroy_account_session_path, :method => :delete, class: 'btn btn-outline-primary'
          - else
            = link_to 'Sign in', new_account_session_path, class: 'btn btn-outline-primary'
            = link_to 'Sign up', new_account_registration_path, class: 'btn btn-outline-primary'
    .container.main
      = yield
      p.notice
        = notice
      p.alert
        = alert

app/views/vendors/_form.html.slim
= form_for @vendor do |f|
  .form-group
    = f.text_field :total_account, class: 'form-control'
  .form-group
    = f.submit "Save", class: 'btn btn-primary'
    = link_to "Cancel", :back, class: 'btn btn-outline-primary'

app/views/vendors/edit.html.slim
| Edit your bank account 
= render 'form'

app/views/vendors/new.html.slim
= render 'form'